/* BCSO Awards workspace - safe fallback that works with the portal's existing modal/db helpers. */
(function(){
const defaultAwards=['Medal of Valor','Life Saving Award','Commendation Medal','Good Conduct Medal','Officer of the Year','Distinguished Service Medal','Meritorious Service Award'];
function allUsers(){return Object.entries(window.db?.users||{}).map(([callsign,u])=>({callsign,...u}));}
window.honorsAdmin=function(){
 const users=allUsers();
 const rows=users.length?users.map(u=>`<tr><td><strong>${esc(u.name||'Unknown')}</strong><small>${esc(u.rank||'Cadet')} • ${esc(u.callsign)}</small></td><td>${esc(u.awards?.length||0)}</td><td><button class="btn green" onclick="awardDeputy('${esc(u.callsign)}')">🏅 Award</button></td></tr>`).join(''):`<tr><td colspan="3" class="empty">No personnel found. Add a Cadet first.</td></tr>`;
 document.getElementById('pageTitle').textContent='Awards & Subdivisions'; document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">PERSONNEL RECOGNITION</span><h3>Awards Cabinet</h3><p class="muted">Award medals and keep a permanent recognition history for each deputy.</p></div></div><div class="award-hero"><div><span>🏅</span><h2>BCSO HONORS</h2><p>Formal department recognition</p></div><div class="award-count">${users.reduce((n,u)=>n+(u.awards?.length||0),0)}<small>Total Awards</small></div></div><div class="section-card"><div class="table-scroll"><table class="table"><thead><tr><th>DEPUTY</th><th>AWARDS</th><th>ACTION</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;
};
window.honors=function(){
 const u=window.current||{}; const awards=u.awards||[]; document.getElementById('pageTitle').textContent='My Awards'; document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">PERSONNEL RECOGNITION</span><h3>My Awards</h3><p class="muted">Your BCSO medals and commendations.</p></div></div><div class="award-hero"><div><span>🏅</span><h2>${esc(u.name||'Deputy')}</h2><p>${esc(u.rank||'Cadet')} • ${esc(u.callsign||'')}</p></div><div class="award-count">${awards.length}<small>My Awards</small></div></div><div class="award-grid">${awards.length?awards.map(a=>`<article class="award-card"><div class="award-icon">${esc(a.icon||'🏅')}</div><div><h3>${esc(a.name||'Award')}</h3><p>${esc(a.citation||'Department recognition')}</p><small>${esc(a.date||'')}</small></div></article>`).join(''):'<div class="section-card empty">You have not received any awards yet.</div>'}</div>`;
};
window.awardDeputy=function(call){const u=window.db?.users?.[call];if(!u)return;const opts=defaultAwards.map(a=>`<option>${a}</option>`).join('');modal(`<span class="eyebrow">BCSO HONORS</span><h2>🏅 Award Medal</h2><p class="muted"><strong>${esc(u.name)}</strong> • ${esc(u.rank||'Cadet')} • ${esc(call)}</p><form onsubmit="saveAward(event,'${esc(call)}')"><label>Award<select id="awardName">${opts}</select></label><label>Award Date<input id="awardDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Citation / Reason<textarea id="awardCitation" required placeholder="Explain why this deputy is receiving the award..."></textarea></label><div class="actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn green">🏅 Award Medal</button></div></form>`)};
window.saveAward=function(e,call){e.preventDefault();const u=window.db.users[call];u.awards=u.awards||[];u.awards.push({name:document.getElementById('awardName').value,date:document.getElementById('awardDate').value,citation:document.getElementById('awardCitation').value,awardedBy:window.current?.name||'BCSO Leadership',icon:'🏅'});save();closeModal();honorsAdmin();toast(`${u.name} received an award`)};
})();