(function(){
window.BCSO_SUBDIVISIONS=[['Air/Water','🚁','Air and marine support'],['CIU','🔎','Criminal Investigation Unit'],['Dispatch','🎧','Communications'],['FTO','📋','Field Training Officer'],['Traffic Unit','🚦','Traffic enforcement'],['SWAT','🛡️','Special Weapons and Tactics'],['K9','🐕','Canine operations'],['STIU','⚡','Specialized investigations'],['VICE','🕶️','Vice enforcement']];
const baseGo=window.go;
window.go=function(page){
 const aliases={subrosters:'subrosters',subdivisions:'subdivisions',newreport:'newReport',myreports:'reports',deputyreports:'reports',manageroster:'subrosters',submanagement:'subdivisions'};
 const fn=window[aliases[page]||page];
 document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
 const titles={dashboard:'Dashboard',roster:'Main Roster',cadets:'Cadet Roster',subrosters:'Subdivision Rosters',subdivisions:'Subdivision Management',reports:'Reports',newreport:'Create Report',sops:'SOP Library',documents:'Document Center',announcements:'Announcements',users:'User Management',statistics:'Statistics',strikes:'Manage Strikes'};
 if(document.getElementById('pageTitle'))document.getElementById('pageTitle').textContent=titles[page]||page.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());
 if(typeof fn==='function'&&page!=='go'){fn();document.querySelector('.sidebar')?.classList.remove('open');return}
 if(typeof baseGo==='function')baseGo(page);
};
window.dashboard=function(){
 const reports=db.reports||[], users=db.users||{}, mine=reports.filter(r=>r.author===current.callsign).length+(+current.reports||0);
 document.getElementById('page').innerHTML=`<div class="dash-hero"><div><span class="eyebrow">BLAINE COUNTY SHERIFF'S OFFICE</span><h1>Welcome back, ${esc(current.name)}</h1><p>${esc(current.rank)} · Callsign ${esc(current.callsign)} · ${esc(current.subdivision||'Unassigned')}</p></div><span class="hero-badge">● SYSTEM ONLINE</span></div><div class="stat-grid"><div class="dash-stat"><div class="stat-icon">▤</div><div><strong>${mine}</strong><span>My Reports</span></div></div><div class="dash-stat"><div class="stat-icon">⚠</div><div><strong>${current.strikes||0}</strong><span>Strikes</span></div></div><div class="dash-stat"><div class="stat-icon">▣</div><div><strong>${reports.length}</strong><span>Department Reports</span></div></div><div class="dash-stat"><div class="stat-icon">♟</div><div><strong>${Object.keys(users).length}</strong><span>Active Staff</span></div></div></div><div class="dash-columns"><section class="dash-panel"><div class="panel-head"><div><span class="eyebrow">QUICK ACCESS</span><h3>Department Tools</h3></div></div><div class="quick-grid"><button onclick="go('newreport')"><b>✎</b><span>Create Report</span><small>Submit a new report</small></button><button onclick="go('roster')"><b>♟</b><span>View Roster</span><small>Department personnel</small></button><button onclick="go('sops')"><b>📖</b><span>SOP Library</span><small>Policies & training</small></button><button onclick="go('announcements')"><b>!</b><span>Announcements</span><small>Department updates</small></button></div></section><section class="dash-panel"><div class="panel-head"><div><span class="eyebrow">LATEST</span><h3>Announcements</h3></div><button class="link-btn" onclick="go('announcements')">View all →</button></div>${(db.announcements||[]).slice(-4).reverse().map(a=>`<div class="notice"><span class="notice-dot"></span><div><strong>${esc(a.title)}</strong><p>${esc(a.text)}</p><small>${esc(a.priority)} · ${esc(a.time)}</small></div></div>`).join('')||'<p class="muted">No announcements.</p>'}</section></div><section class="dash-panel"><div class="panel-head"><div><span class="eyebrow">SPECIALIZED UNITS</span><h3>BCSO Subdivisions</h3></div><button class="link-btn" onclick="go('subrosters')">View rosters →</button></div><div class="mini-subs">${BCSO_SUBDIVISIONS.map(d=>`<div><b>${d[1]}</b><span>${d[0]}</span><small>${Object.values(users).filter(u=>u.subdivision===d[0]).length} members</small></div>`).join('')}</div></section>`;
};
window.subrosters=function(){document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">PERSONNEL</span><h3>Subdivision Rosters</h3><p class="muted">Official BCSO specialized units.</p></div></div><div class="sub-grid">${BCSO_SUBDIVISIONS.map(d=>`<div class="sub-card"><div class="sub-icon">${d[1]}</div><h3>${d[0]}</h3><p>${d[2]}</p><span class="badge">${Object.values(db.users||{}).filter(u=>u.subdivision===d[0]).length} members</span><div class="actions"><button class="btn secondary" onclick="showSub('${d[0]}')">View Roster →</button></div></div>`).join('')}</div>`};
window.subdivisions=function(){if(current.role!=='Admin'){toast('Admin access required');return}subrosters()};
window.showSub=function(name){const p=Object.entries(db.users||{}).filter(([c,u])=>u.subdivision===name);modal(`<span class="eyebrow">SUBDIVISION ROSTER</span><h2>${esc(name)}</h2><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Callsign</th><th>Rank</th><th>Role</th></tr></thead><tbody>${p.map(([c,u])=>`<tr><td>${esc(u.name)}</td><td>${c}</td><td>${esc(u.rank)}</td><td>${esc(u.role)}</td></tr>`).join('')||'<tr><td colspan="4">No members assigned.</td></tr>'}</tbody></table></div>`)};
})();
