/* BCSO configurable report builder */
(function(){
 const TYPES_KEY='bcsoReportTypes';
 const defaultTypes=[{id:'arrest',name:'Arrest Report',description:'Document an arrest and charges.',fields:[{label:'Subject Name',type:'text',required:true},{label:'Charges',type:'textarea',required:true},{label:'Incident Date',type:'date',required:true},{label:'Narrative',type:'textarea',required:true}],approval:true},{id:'traffic',name:'Traffic Stop Report',description:'Document a traffic stop.',fields:[{label:'Driver Name',type:'text',required:true},{label:'Vehicle / Plate',type:'text',required:true},{label:'Location',type:'text',required:true},{label:'Reason for Stop',type:'text',required:true},{label:'Narrative',type:'textarea',required:true}],approval:false},{id:'general',name:'General Incident Report',description:'General department incident documentation.',fields:[{label:'Incident Type',type:'text',required:true},{label:'Location',type:'text',required:true},{label:'Narrative',type:'textarea',required:true}],approval:false}];
 function getTypes(){try{return JSON.parse(localStorage.getItem(TYPES_KEY))||defaultTypes}catch(e){return defaultTypes}}
 function saveTypes(a){localStorage.setItem(TYPES_KEY,JSON.stringify(a))}
 function fEsc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 window.reportBuilder=function(){if(!current||current.role!=='Admin'){toast('Admin access required');return}const ts=getTypes();document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">ADMINISTRATION</span><h3>Report Builder</h3><p class="muted">Create and customize report types without editing the website code.</p></div><button class="btn green" onclick="newReportType()">+ New Report Type</button></div><div class="grid2"><div>${ts.map(t=>`<div class="section-card" style="margin-bottom:14px"><div style="display:flex;justify-content:space-between;gap:15px"><div><h3>${fEsc(t.name)}</h3><p class="muted">${fEsc(t.description)}</p></div><span class="badge">${t.fields.length} fields</span></div><p class="muted">${t.fields.map(x=>fEsc(x.label)+(x.required?' *':'')).join(' • ')}</p><div class="actions"><button class="btn secondary" onclick="editReportType('${t.id}')">Edit</button><button class="btn secondary" style="color:#e39b92" onclick="deleteReportType('${t.id}')">Delete</button></div></div>`).join('')}</div><div class="section-card"><h3>How it works</h3><p class="muted">Build a report by adding fields. Deputies will see every active report type under Create Report.</p><ul class="muted"><li>Text</li><li>Long narrative</li><li>Date</li><li>Number</li><li>Dropdown</li><li>Checkbox</li></ul></div></div>`}
 window.newReportType=function(existing){const t=existing||{id:'r'+Date.now(),name:'',description:'',fields:[],approval:false};window._editingReport=t;modal(`<span class="eyebrow">REPORT DESIGNER</span><h2>${existing?'Edit':'Create'} Report Type</h2><form onsubmit="saveReportType(event)"><div class="form-grid"><label>Report Name<input id="rtName" required value="${fEsc(t.name)}" placeholder="Supervisor General Report"></label><label>Approval<select id="rtApproval"><option value="false" ${!t.approval?'selected':''}>No supervisor approval</option><option value="true" ${t.approval?'selected':''}>Supervisor approval required</option></select></label><label class="full">Description<textarea id="rtDesc" style="min-height:70px">${fEsc(t.description)}</textarea></label></div><h3 style="margin-top:20px">Fields</h3><div id="reportFields">${t.fields.map((x,i)=>fieldEditor(x,i)).join('')}</div><button type="button" class="btn secondary" onclick="addReportField()">+ Add Field</button><div class="actions"><button class="btn green">SAVE REPORT TYPE</button></div></form>`)}
 function fieldEditor(x,i){return `<div class="section-card" style="margin:10px 0;padding:14px"><div class="form-grid"><label>Field Label<input class="rf-label" value="${fEsc(x.label)}" required></label><label>Field Type<select class="rf-type"><option ${x.type==='text'?'selected':''}>text</option><option ${x.type==='textarea'?'selected':''}>textarea</option><option ${x.type==='date'?'selected':''}>date</option><option ${x.type==='number'?'selected':''}>number</option><option ${x.type==='select'?'selected':''}>select</option><option ${x.type==='checkbox'?'selected':''}>checkbox</option></select></label><label><input class="rf-required" type="checkbox" ${x.required?'checked':''} style="width:auto"> Required</label><button type="button" class="btn secondary" onclick="this.closest('.section-card').remove()">Remove</button></div></div>`}
 window.addReportField=function(){document.getElementById('reportFields').insertAdjacentHTML('beforeend',fieldEditor({label:'',type:'text',required:false},Date.now()))}
 window.saveReportType=function(e){e.preventDefault();const old=window._editingReport;const fields=[...document.querySelectorAll('#reportFields .section-card')].map(x=>({label:x.querySelector('.rf-label').value.trim(),type:x.querySelector('.rf-type').value,required:x.querySelector('.rf-required').checked})).filter(x=>x.label);const t={id:old.id,name:document.getElementById('rtName').value.trim(),description:document.getElementById('rtDesc').value.trim(),approval:document.getElementById('rtApproval').value==='true',fields};const ts=getTypes(),idx=ts.findIndex(x=>x.id===t.id);if(idx>=0)ts[idx]=t;else ts.push(t);saveTypes(ts);closeModal();reportBuilder();toast('Report type saved')}
 window.editReportType=function(id){const t=getTypes().find(x=>x.id===id);if(t)newReportType(t)};window.deleteReportType=function(id){if(!confirm('Delete this report type?'))return;saveTypes(getTypes().filter(x=>x.id!==id));reportBuilder();toast('Report type deleted')};
 window.configurableReports=function(){const ts=getTypes();document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">DEPUTY TOOLS</span><h3>Create Report</h3><p class="muted">Select a report type and complete the required fields.</p></div></div><div class="grid2"><div>${ts.map(t=>`<button class="section-card" style="width:100%;text-align:left;margin-bottom:12px;color:inherit;cursor:pointer" onclick="openConfigReport('${t.id}')"><h3>${fEsc(t.name)}</h3><p class="muted">${fEsc(t.description)}</p><span class="badge">${t.fields.length} fields${t.approval?' • Supervisor review':''}</span></button>`).join('')}</div><div class="section-card"><h3>Report types</h3><p class="muted">Administrators can add or change these at any time from Administration → Report Builder.</p></div></div>`}
 window.openConfigReport=function(id){const t=getTypes().find(x=>x.id===id);if(!t)return;modal(`<span class="eyebrow">NEW REPORT</span><h2>${fEsc(t.name)}</h2><form onsubmit="submitConfigReport(event,'${t.id}')"><div class="form-grid">${t.fields.map((x,i)=>`<label class="${x.type==='textarea'?'full':''}">${fEsc(x.label)}${x.required?' *':''}${x.type==='textarea'?`<textarea class="crf" data-label="${fEsc(x.label)}" ${x.required?'required':''}></textarea>`:x.type==='checkbox'?`<input class="crf" data-label="${fEsc(x.label)}" type="checkbox">`:`<input class="crf" data-label="${fEsc(x.label)}" type="${x.type==='date'||x.type==='number'?x.type:'text'}" ${x.required?'required':''}>`}</label>`).join('')}</div><button class="btn green">SUBMIT REPORT</button></form>`)}
 window.submitConfigReport=function(e,id){e.preventDefault();const t=getTypes().find(x=>x.id===id);const data={reportType:t.name,submittedBy:current?.name||'Unknown',callsign:current?.callsign||'',submittedAt:new Date().toISOString(),fields:{}};document.querySelectorAll('.crf').forEach(x=>data.fields[x.dataset.label]=x.type==='checkbox'?x.checked:x.value);db.reports=db.reports||[];db.reports.push(data);save();closeModal();toast(t.approval?'Report submitted for supervisor review':'Report submitted successfully')}
})();
