const DEMO={'1108':{name:'Director Account',role:'Admin',rank:'Director',password:'SecureDelta2025',subdivision:'Administration',reports:18,strikes:0},'1128':{name:'Supervisor Account',role:'Supervisor',rank:'Lieutenant',password:'SecureDelta2025',subdivision:'Patrol Division',reports:11,strikes:1},'1300':{name:'Ranger Account',role:'Ranger',rank:'Ranger',password:'SecureDelta2025',subdivision:'Game Warden',reports:6,strikes:0}};
const ranks={Ranger:['Ranger','Ranger 1st Class','Ranger 2nd Class','Warden 1st Class','Warden 2nd Class'],Supervisor:['Corporal','Sergeant','Lieutenant','Captain'],Admin:['Deputy Commissioner','Assistant Commissioner','Commissioner','Deputy Director','Assistant Director','Director']};
const divisions=[['MCU','🔍','Investigations'],['K9','🐕','Canine operations'],['Game Warden','🌲','Game and wildlife enforcement'],['AIR','🚁','Air support'],['FTO','📋','Training'],['Dispatch','🎧','Communications'],['SOG','⚡','Tactical operations']];
let db=JSON.parse(localStorage.getItem('bcsoDB')||'null')||{users:{...DEMO},reports:[],documents:[],sops:[],announcements:[{title:'Welcome to the BCSO Portal',text:'Department portal is online. Please review current SOPs and announcements.',priority:'Important',author:'1108',time:new Date().toLocaleString()}],subs:{}};let current=null;let soundOn=localStorage.getItem('bcsoSound')!=='off';
function save(){localStorage.setItem('bcsoDB',JSON.stringify(db))}function togglePassword(id){const x=document.getElementById(id);x.type=x.type==='password'?'text':'password'}
function beep(freq=620,duration=.07){if(!soundOn)return;try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+duration)}catch(e){}}
function toggleSound(){soundOn=!soundOn;localStorage.setItem('bcsoSound',soundOn?'on':'off');document.getElementById('soundLabel').textContent=soundOn?'Sounds On':'Sounds Off';beep(700,.08)}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function login(e){e.preventDefault();const c=document.getElementById('loginCallsign').value.trim(),p=document.getElementById('loginPassword').value,u=db.users[c];if(!u||u.password!==p){beep(180,.12);document.getElementById('loginError').textContent='Invalid callsign or password.';return}current={...u,callsign:c};sessionStorage.setItem('bcsoCurrent',JSON.stringify(current));beep(800,.12);openApp()}
function openApp(){document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');document.getElementById('sideName').textContent=current.name;document.getElementById('sideRole').textContent=current.role;document.getElementById('sideRank').textContent=`${current.rank} • Callsign ${current.callsign}`;document.getElementById('avatar').textContent=(current.name||'?').split(' ').map(x=>x[0]).slice(0,2).join('');document.querySelectorAll('.admin-only').forEach(x=>x.style.display=current.role==='Admin'?'block':'none');go('dashboard')}
function logout(){beep(420,.08);sessionStorage.removeItem('bcsoCurrent');current=null;location.reload()}
function go(page){beep(560,.035);document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('pageTitle').textContent=page==='users'?'User Management':page==='sops'?'SOP Library':page.charAt(0).toUpperCase()+page.slice(1);const f={dashboard,roster,reports,sops,documents,announcements,subdivisions,users,settings};if(f[page])f[page]();document.querySelector('.sidebar').classList.remove('open')}
document.addEventListener('click',e=>{const b=e.target.closest('#sideNav button');if(b)go(b.dataset.page)});
function dashboard(){const mine=db.reports.filter(r=>r.author===current.callsign).length;document.getElementById('page').innerHTML=`<div class="welcome"><div><span class="eyebrow">PERSONAL DASHBOARD</span><h1>Welcome back, ${esc(current.name)}</h1><p class="muted">${current.rank} • Callsign ${current.callsign} • ${esc(current.subdivision||'Unassigned')}</p></div></div><div class="cards"><div class="card"><div class="metric">${mine+Number(current.reports||0)}</div><div class="metric-label">My Reports</div></div><div class="card"><div class="metric">${current.strikes||0}</div><div class="metric-label">Strikes</div></div><div class="card"><div class="metric">${db.reports.length+42}</div><div class="metric-label">Department Reports</div></div><div class="card"><div class="metric">${Object.keys(db.users).length}</div><div class="metric-label">Active Staff</div></div></div><div class="grid2"><div class="section-card"><h3>Current Assignment</h3><p class="muted">Subdivision</p><strong>${esc(current.subdivision||'Unassigned')}</strong><p class="muted">Rank</p><strong>${esc(current.rank)}</strong></div><div class="section-card"><h3>Recent Announcements</h3>${db.announcements.slice(-3).reverse().map(a=>`<div class="list-item"><strong>${esc(a.title)} <span class="badge ${a.priority==='Urgent'?'red':a.priority==='Important'?'gold':''}">${a.priority}</span></strong><p>${esc(a.text)}</p></div>`).join('')}</div></div>`}
function roster(){document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">PERSONNEL</span><h3>Department Roster</h3></div><input class="search" id="rosterSearch" oninput="filterRoster()" placeholder="Search personnel..."></div><div class="table-wrap"><table class="table"><thead><tr><th>NAME</th><th>CALLSIGN</th><th>RANK</th><th>ROLE</th><th>ASSIGNMENT</th><th>STATUS</th></tr></thead><tbody id="rosterBody">${Object.entries(db.users).map(([c,u])=>`<tr><td>${esc(u.name)}</td><td>${c}</td><td>${esc(u.rank)}</td><td><span class="badge">${u.role}</span></td><td>${esc(u.subdivision||'Unassigned')}</td><td class="status">● Active</td></tr>`).join('')}</tbody></table></div>`}
function filterRoster(){const q=document.getElementById('rosterSearch').value.toLowerCase();document.querySelectorAll('#rosterBody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')}
function reports(){document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">DOCUMENTATION</span><h3>Reports</h3><p class="muted">Submit and track department reports.</p></div><button class="btn green" onclick="newReport()">+ New Report</button></div><div class="section-card"><h3>Recent Reports</h3>${db.reports.length?`<div class="table-wrap"><table class="table"><thead><tr><th>TYPE</th><th>AUTHOR</th><th>DATE</th><th>STATUS</th></tr></thead><tbody>${db.reports.slice().reverse().map(r=>`<tr><td>${esc(r.type)}</td><td>${esc(r.authorName)} (${r.author})</td><td>${esc(r.time)}</td><td><span class="badge">Submitted</span></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No reports submitted yet.</p>'}</div>`}
function newReport(){modal(`<span class="eyebrow">NEW REPORT</span><h2>Submit Department Report</h2><form onsubmit="submitReport(event)"><div class="form-grid"><label>Report Type<select id="reportType"><option>Warden-Involved Weapon Discharge Report</option><option>Arrest Report</option><option>Citation Report</option><option>Pursuit Report</option></select></label><label>Subject / Case<input id="reportSubject" required></label><label class="full">Details<textarea id="reportDetails" required></textarea></label></div><button class="btn green">Submit Report</button></form>`)}
function submitReport(e){e.preventDefault();db.reports.push({type:document.getElementById('reportType').value,subject:document.getElementById('reportSubject').value,details:document.getElementById('reportDetails').value,author:current.callsign,authorName:current.name,time:new Date().toLocaleString()});save();beep(900,.08);closeModal();reports();toast('Report submitted successfully')}
function announcements(){document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">COMMUNICATIONS</span><h3>Announcements</h3><p class="muted">Department-wide notifications.</p></div>${current.role==='Admin'?'<button class="btn green" onclick="newAnnouncement()">+ New Announcement</button>':''}</div><div class="list">${db.announcements.slice().reverse().map((a,i)=>`<div class="list-item"><strong>${esc(a.title)} <span class="badge ${a.priority==='Urgent'?'red':a.priority==='Important'?'gold':''}">${a.priority}</span></strong><p>${esc(a.text)}</p><small class="muted">${esc(a.author)} • ${esc(a.time)}</small>${current.role==='Admin'?`<button class="btn secondary" style="margin-top:10px" onclick="deleteAnnouncement(${db.announcements.length-1-i})">Delete</button>`:''}</div>`).join('')}</div>`}
function newAnnouncement(){modal(`<span class="eyebrow">ADMIN</span><h2>Create Announcement</h2><form onsubmit="submitAnnouncement(event)"><div class="form-grid"><label>Title<input id="aTitle" required></label><label>Priority<select id="aPriority"><option>Normal</option><option>Important</option><option>Urgent</option></select></label><label class="full">Message<textarea id="aText" required></textarea></label></div><button class="btn green">Publish</button></form>`)}
function submitAnnouncement(e){e.preventDefault();db.announcements.push({title:document.getElementById('aTitle').value,text:document.getElementById('aText').value,priority:document.getElementById('aPriority').value,author:current.callsign,time:new Date().toLocaleString()});save();beep(850,.08);closeModal();announcements();toast('Announcement published')}
function deleteAnnouncement(i){if(confirm('Delete this announcement?')){db.announcements.splice(i,1);save();beep(250,.08);announcements();toast('Announcement deleted')}}
function sops(){const items=db.sops.length?db.sops:[{title:'General Operations',text:'Core expectations, conduct and patrol procedures.'},{title:'Traffic Enforcement',text:'Traffic stops, pursuits, radar and TEU procedures.'},{title:'Use of Force',text:'Approved standards for lawful and proportional force.'},{title:'Radio & Communications',text:'Radio discipline, codes and communications procedures.'},{title:'Training Materials',text:'Department training resources and best practices.'}];document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">POLICY CENTER</span><h3>Standard Operating Procedures</h3><p class="muted">Policies, training materials and operational guidance.</p></div>${current.role==='Admin'?'<button class="btn green" onclick="newSop()">+ Add SOP</button>':''}</div><div class="sub-grid">${items.map((x,i)=>`<div class="sub-card"><div class="sub-icon">📖</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p><button class="btn secondary" onclick="modal('<span class=eyebrow>SOP</span><h2>${esc(x.title)}</h2><p>${esc(x.text)}</p>')">Open Document</button></div>`).join('')}</div>`}
function newSop(){modal(`<span class="eyebrow">ADMIN • SOP LIBRARY</span><h2>Add SOP Document</h2><form onsubmit="saveSop(event)"><div class="form-grid"><label>Title<input id="sTitle" required></label><label>Category<input id="sCat"></label><label class="full">Document Content<textarea id="sText" required></textarea></label></div><button class="btn green">Save SOP</button></form>`)}function saveSop(e){e.preventDefault();db.sops.push({title:document.getElementById('sTitle').value,text:document.getElementById('sText').value,category:document.getElementById('sCat').value});save();closeModal();sops();toast('SOP added to library')}
function documents(){document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">DOCUMENT CENTER</span><h3>Department Documents</h3><p class="muted">Store policies, forms, training files and internal resources.</p></div>${current.role==='Admin'?'<button class="btn green" onclick="newDocument()">+ Add Document</button>':''}</div><div class="sub-grid">${db.documents.length?db.documents.map((d,i)=>`<div class="sub-card"><div class="sub-icon">📄</div><h3>${esc(d.title)}</h3><p>${esc(d.category||'Department document')}</p><button class="btn secondary" onclick="modal('<span class=eyebrow>DOCUMENT</span><h2>${esc(d.title)}</h2><p>${esc(d.text)}</p>')">View</button>${current.role==='Admin'?` <button class="btn secondary" onclick="deleteDocument(${i})">Delete</button>`:''}</div>`).join(''):'<div class="section-card"><h3>No documents yet</h3><p class="muted">Admins can add documents here.</p></div>'}</div>`}
function newDocument(){modal(`<span class="eyebrow">ADMIN • DOCUMENT CENTER</span><h2>Add Department Document</h2><form onsubmit="saveDocument(event)"><div class="form-grid"><label>Title<input id="dTitle" required></label><label>Category<input id="dCat" placeholder="Policy, Training, Form..."></label><label class="full">Document Text / Notes<textarea id="dText" required></textarea></label></div><button class="btn green">Add Document</button></form>`)}function saveDocument(e){e.preventDefault();db.documents.push({title:document.getElementById('dTitle').value,category:document.getElementById('dCat').value,text:document.getElementById('dText').value});save();closeModal();documents();toast('Document added')}
function deleteDocument(i){if(confirm('Delete this document?')){db.documents.splice(i,1);save();documents();toast('Document deleted')}}
function subdivisions(){if(current.role!=='Admin')return go('dashboard');document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">ADMINISTRATION</span><h3>Subdivisions</h3><p class="muted">Manage specialized unit leadership and membership.</p></div></div><div class="sub-grid">${divisions.map(d=>`<div class="sub-card"><div class="sub-icon">${d[1]}</div><h3>${d[0]}</h3><p>${d[2]}</p><strong>${Object.values(db.users).filter(u=>u.subdivision===d[0]).length} members</strong><div class="actions" style="margin-top:14px"><button class="btn secondary" onclick="manageSub('${d[0]}')">Manage</button></div></div>`).join('')}</div>`}
function manageSub(name){modal(`<span class="eyebrow">SUBDIVISION</span><h2>${esc(name)}</h2><p class="muted">Assign a supervisor leader and members.</p><label>Leader<select id="leaderSelect">${Object.entries(db.users).filter(([c,u])=>u.role!=='Ranger').map(([c,u])=>`<option value="${c}">${esc(u.name)} (${esc(u.rank)})</option>`).join('')}</select></label><br><button class="btn green" onclick="closeModal()">Save Assignment</button>`)}
function users(){if(current.role!=='Admin')return go('dashboard');document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">ADMINISTRATION</span><h3>User Management</h3><p class="muted">Create, assign and manage department accounts.</p></div><button class="btn green" onclick="newUser()">+ Create User</button></div><div class="table-wrap"><table class="table"><thead><tr><th>NAME</th><th>CALLSIGN</th><th>ROLE</th><th>RANK</th><th>ASSIGNMENT</th><th>ACTIONS</th></tr></thead><tbody>${Object.entries(db.users).map(([c,u])=>`<tr><td>${esc(u.name)}</td><td>${c}</td><td>${u.role}</td><td>${u.rank}</td><td>${u.subdivision||'Unassigned'}</td><td>${c===current.callsign?'—':`<button class="btn secondary" onclick="deleteUser('${c}')">Delete</button>`}</td></tr>`).join('')}</tbody></table></div>`}
function newUser(){modal(`<span class="eyebrow">ADMIN • USER CREATION</span><h2>Create User</h2><form onsubmit="createUser(event)"><div class="form-grid"><label>Full Name<input id="uName" required></label><label>Callsign<input id="uCallsign" required inputmode="numeric"></label><label>Role<select id="uRole" onchange="updateRanks()"><option>Ranger</option><option>Supervisor</option><option>Admin</option></select></label><label>Rank<select id="uRank"></select></label></div><button class="btn green">Generate Account & Password</button></form>`);updateRanks()}
function updateRanks(){const role=document.getElementById('uRole').value;document.getElementById('uRank').innerHTML=ranks[role].map(r=>`<option>${r}</option>`).join('')}
function createUser(e){e.preventDefault();const c=document.getElementById('uCallsign').value.trim();if(db.users[c])return alert('Callsign already exists.');const password=securePassword();const u={name:document.getElementById('uName').value,role:document.getElementById('uRole').value,rank:document.getElementById('uRank').value,password,subdivision:'Unassigned',reports:0,strikes:0};db.users[c]=u;save();modal(`<span class="eyebrow">ACCOUNT CREATED</span><h2>${esc(u.name)}</h2><p>Show these credentials once and send them securely.</p><div class="credential"><b>Callsign</b><br><code>${c}</code></div><div class="credential"><b>Password</b><br><code>${password}</code></div><button class="btn green" onclick="copyText('${c} / ${password}')">Copy Credentials</button>`);beep(950,.08)}
function securePassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';let s='';for(let i=0;i<16;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}function copyText(t){navigator.clipboard?.writeText(t);toast('Copied to clipboard');beep(720,.05)}function deleteUser(c){if(c===current.callsign)return alert('You cannot delete your own account.');if(confirm('Delete this user account?')){delete db.users[c];save();users();toast('User deleted')}}
function settings(){if(current.role!=='Admin')return go('dashboard');document.getElementById('page').innerHTML=`<div class="heading"><div><span class="eyebrow">SYSTEM CONTROL</span><h3>System Settings</h3><p class="muted">Portal preferences and administrative controls.</p></div></div><div class="grid2"><div class="section-card"><h3>Interface</h3><p class="muted">BCSO black, gold, brown and green command theme.</p><button class="btn secondary" onclick="toggleSound()">Toggle UI Sounds</button></div><div class="section-card"><h3>Local Data</h3><p class="muted">Current prototype stores demo data in this browser. Production Supabase will replace this storage.</p><button class="btn secondary" onclick="if(confirm('Clear local demo data?')){localStorage.removeItem('bcsoDB');location.reload()}">Reset Local Demo Data</button></div></div>`}
function modal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').classList.add('show')}function closeModal(){document.getElementById('modal').classList.remove('show')}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
document.getElementById('loginForm').addEventListener('submit',login);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});const saved=sessionStorage.getItem('bcsoCurrent');if(saved){current=JSON.parse(saved);openApp()};
